### ISSUE TITLE
psql within snap is not usable for operator use

### ISSUE THREAD

**Issue by odufourc** [canonical/charmed-postgresql-snap#19]
## Steps to reproduce
1.  Deploy charmed postgresql channel 14/stable
2. Retrieve the operator password through the charm's action
3. use charmed-postgresql.psql to connect to database

## Expected behavior
Having the connection to work

### if using IP address 
ubuntu@jaas-pgsql-0:~$ charmed-postgresql.psql --host=192.168.122.55 --username operator --password
Password:
psql: error: connection to server at "192.168.122.55", port 5432 failed: could not create socket: Permission denied

### if using Unix socket 
ubuntu@jaas-pgsql-0:~$ charmed-postgresql.psql --host=/tmp/ --username operator --password
Password:
psql: error: connection to server on socket "/tmp//.s.PGSQL.5432" failed: FATAL:  no pg_hba.conf entry for host "[local]", user "operator", database "operator", no encryption

## Versions
Operating system: Ubuntu Jammy 22.04
Juju : 3.2.0
Snap: charmed-postgresql  14.7 , revision 31 from latest/stable channel

### attempt to connect with psql client from snap 
ubuntu@jaas-pgsql-0:~$ charmed-postgresql.psql --host=192.168.122.55 --username operator --password
Password:
psql: error: connection to server at "192.168.122.55", port 5432 failed: could not create socket: Permission denied

### logs from auditd/apparmor, showing restriction from the snap configuration
Aug 07 05:42:07 jaas-pgsql-0 systemd[1460]: Started snap.charmed-postgresql.psql.556d399d-fe99-4abc-97f3-a4e659bfc10b.scope.
Aug 07 05:42:09 jaas-pgsql-0 audit[487529]: AVC apparmor="DENIED" operation="create" profile="snap.charmed-postgresql.psql" pid=487529 comm="psql" family="inet" sock_type="stream" protocol=0 requested_mask="create" denied_mask="create"
Aug 07 05:42:09 jaas-pgsql-0 kernel: audit: type=1400 audit(1691386929.070:169): apparmor="DENIED" operation="create" profile="snap.charmed-postgresql.psql" pid=487529 comm="psql" family="inet" sock_type="stream" protocol=0 requested_mask="create" denied_mask="create"

### content of pg_hba.conf (for Unix socket attempt)
ubuntu@jaas-pgsql-0:~$ sudo cat /var/snap/charmed-postgresql/common/var/lib/postgresql/pg_hba.conf
\# Do not edit this file manually!
\# It will be overwritten by Patroni!
local all backup peer map=operator
hostssl replication replication 127.0.0.1/32 md5
hostssl all all 0.0.0.0/0 md5
hostssl     replication    replication    192.168.122.16/0    md5

## current workaround
If running on Ubuntu Jammy, installing postgresql client from Debian's package, helps to circumvent the issue.
$ sudo apt install  postgresql-client-14
$ psql --host 192.168.122.55 --username operator --dbname jimm --password

## Additional context
At a first glance, 2 things could be improved to allow more flexibility : 
1. Change snap configuration to allow charmed-postgresql.psql client to connect to the server through the IP address
2. Tweak ```/var/snap/charmed-postgresql/common/var/lib/postgresql/pg_hba.conf``` to allow operator to connect to the database if using the Unix socket

**Comment by dragomirp** [comment]
Hi, @odufourc, on latest edge of the charm I was able to log in by IP from within the machine:
```
ubuntu@juju-0ac78a-0:/root$ psql -U operator -W -h 10.233.240.86 postgres
Password: 
psql (14.9 (Ubuntu 14.9-0ubuntu0.22.04.1))
Type "help" for help.

postgres=#
```
On latest edge `charmed-postgresql.psql` is aliased to `psql`.

I'll see how we want local socket connections to look and will open a follow up issue on the charm repo, since it's a matter of charm configuration.

**Comment by taurus-forever** [comment]
Dear @odufourc thank you for the report!

re: `1. Change snap configuration to allow charmed-postgresql.psql ...`

As @dragomirp mentioned, It has been addressed already in https://warthogs.atlassian.net/browse/DPE-2050 and improved in https://warthogs.atlassian.net/browse/DPE-2090 (unfortunately available in revisions from `14/edge` only at the moment).

re: `2. Tweak config to allow operator to connect to the database if using the Unix socket`

Do you still need socket access if IP access addressed above?
The open question is: should user have passwordless access into database using psql?
Security VS usability. CC: Mohamed.

**Comment by odufourc** [comment]
Hello @dragomirp and @taurus-forever 

Thank you for your prompt replies. It is appreciated.
I didn't realise for the first option, this was fixed on latest/edge of the snap. Sadly the charm deploy the stable release with no way to tweak it aside from logging onto the machine.

Regarding the second option with using the Unix socket. It is certainly not a strong requirement, however I would add this option as "nice to have" for sysadmins, especially if considering scenarios where for example changes are applied to ```pg_hba.conf``` happen to be more restrictive later on from which network to connect or simply if for any reason there is an issue with the network stack (like the snap having a regression).

Also it is still possible to ensure that a password is required even when connecting from the Unix socket with the right configuration. So security shouldn't be a concern here.
In my opinion have a line in ```pg_hba.conf``` like ```local all operator scram-sha-256``` would be more than sufficient and still require the operator to be prompted to give a password.

**Comment by dragomirp** [comment]
Hi, @odufourc, I've created https://github.com/canonical/postgresql-operator/issues/213 to track this on the charm repo.

**Comment by dragomirp** [comment]
Hi, @odufourc, latest edge revision (323) should allow socket connections.
